### ISSUE TITLE
We couldn’t deliver this payload: Service Timeout

### ISSUE THREAD

**Issue by Juev** [piranha/webhooker#2]
Если задача, что запускается при появлении вехука выполняется хотя бы минуту, в Github появляется сообщение о невозможности доставить сообщение, так как вовремя не появляется ответ.

Если же выполнение команды проводиться достаточно быстро, в Github появляется отметка об успешном отправлении сообщения.

Может стоит отправлять уведомление еще до того, как закончиться выполнятся требуемая команда??

**Comment by Juev** [comment]
Да, я пытался прописывать в команде запуска переход в фон, но безрезультатно.

**Comment by piranha** [comment]
Если я отвечу до того, как выполнится команда - то даже если она помрëт, гитхаб об этом не узнает и не перепошлëт сообщение. Так и должно быть, вообще-то, просто надо переделать команду. Я подумаю, может стоит это хендлить в самом вебхукере.

**Comment by Juev** [comment]
Ммм, а зачем гитхабу сообщать о том, что что-то произошло?
Мы должны ему ответить, что приняли запрос и только. А дальше, что будем делать, это уже наши проблемы. Разве не так?

**Comment by piranha** [comment]
Не так. Гитхаб шлëт пейлоад, если удалось обработать, то всë ок. Если приложение зафейлилось, то гитхабу хорошо бы об этом знать, чтоб отправить нотификацию еще раз - вдруг ты рестартовал сервер, или базу данных, или роутинг упал, или еще что-то произошло. А минута - это таймаут, всë разумно.
