### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by Juev** [piranha/webhooker#3]
На данный момент все параметры программы передаются через командную строку.

Почему бы не упростить и не создать конфигурационные файлы? В формате yaml или json, особого значения не имеет. Расположение файлов:

1. Если есть ~/.webhook использовать его
1. Если есть /etc/webhook.conf использовать его (имя файла и расположение для примера)
1. В противном случае использовать дефолтные значения

Что позволит задать файл конфигурации и затем уже использовать запуск программы без параметров в командной строке.

**Comment by piranha** [comment]
By design, don't want that.
