### ISSUE TITLE
Обязательные параметры?

### ISSUE THREAD

**Issue by Juev** [piranha/webhooker#4]
Попытался использовать запуск webhooker пропустив параметр -i 127.0.0.1

При этом получил ошибку при попытке выполнения хука о том, что sh не может выполнить команду. Не анализировал, в чем может быть причина, но указав параметр, от ошибки избавился. 

Почему бы не задать параметры со значениями по умолчанию? Тот же порт и айпи-адрес, могут иметь значения, которые не потребуется каждый раз при запуске переопределять.

**Comment by piranha** [comment]
Good one.
